name: Run Sisimpur Brain Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust if your project needs a different version

      - name: Run script in sisimpur-brain
        run: |
          cd sisimpur-brain

          echo "Creating virtual environment..."
          python -m venv venv
          source venv/bin/activate

          echo "Installing requirements..."
          pip install --upgrade pip
          pip install -r requirements.txt

          echo "Setting API key..."
          export GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}

          echo "Running script..."
          python main.py test_data/1_bangla.jpg
